### ISSUE TITLE
Not working on index.html

### ISSUE THREAD

**Issue by bkyf** [hzsrc/js-conditional-compile-loader#6]
Hi,

I am developing something in Vue and I want conditional complilation at the entry point for my application - i.e. index.html.
However,  js-conditional-compile-loader does not seem to be working there.

Can you help me please?

**Comment by hzsrc** [comment]
You can use it in any ​file.
About html files, you can set up a rule in webpack `rules` for `.html` file use this loader:
```js
    {
                test: /\.html$/,
                loader: 'js-conditional-compile-loader',
                options: {...}
     }
```
